/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.estoyperdido;

/**
 *
 * @author Eimygame
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Anastasia = new javax.swing.JLabel();
        Bonifacio = new javax.swing.JLabel();
        BSa = new javax.swing.JButton();
        BGl = new javax.swing.JButton();
        BE = new javax.swing.JButton();
        BDa = new javax.swing.JButton();
        Gl = new javax.swing.JTabbedPane();
        Da = new javax.swing.JTabbedPane();
        Sa = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Anastasia.setIcon(new javax.swing.ImageIcon("C:\\Users\\Eimygame\\Documents\\NetBeansProjects\\Estoyperdido\\imagen\\anastacia.jpg")); // NOI18N
        getContentPane().add(Anastasia);
        Anastasia.setBounds(20, 20, 222, 243);

        Bonifacio.setIcon(new javax.swing.ImageIcon("C:\\Users\\Eimygame\\Documents\\NetBeansProjects\\Estoyperdido\\imagen\\Anastacio.jpg")); // NOI18N
        getContentPane().add(Bonifacio);
        Bonifacio.setBounds(10, 402, 222, 276);

        BSa.setText("Subir archivo");
        getContentPane().add(BSa);
        BSa.setBounds(350, 150, 95, 23);

        BGl.setText("Generar llave");
        BGl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BGlActionPerformed(evt);
            }
        });
        getContentPane().add(BGl);
        BGl.setBounds(370, 520, 97, 23);

        BE.setText("Encriptar");
        BE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEActionPerformed(evt);
            }
        });
        getContentPane().add(BE);
        BE.setBounds(350, 230, 97, 23);

        BDa.setText("Desencriptar");
        getContentPane().add(BDa);
        BDa.setBounds(370, 790, 97, 23);
        getContentPane().add(Gl);
        Gl.setBounds(260, 410, 323, 100);
        getContentPane().add(Da);
        Da.setBounds(270, 570, 310, 210);
        getContentPane().add(Sa);
        Sa.setBounds(320, 40, 177, 92);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BGlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BGlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BGlActionPerformed

    private void BEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Anastasia;
    private javax.swing.JButton BDa;
    private javax.swing.JButton BE;
    private javax.swing.JButton BGl;
    private javax.swing.JButton BSa;
    private javax.swing.JLabel Bonifacio;
    private javax.swing.JTabbedPane Da;
    private javax.swing.JTabbedPane Gl;
    private javax.swing.JTabbedPane Sa;
    // End of variables declaration//GEN-END:variables
}
